### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by MikeSalisbury** [MikeSalisbury/eventbright#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
Excellent progress on auth. Demo login works great, as does creating a new account. I can log in and out with no problem when I have the right credentials. And you implemented the separate email page first, as Eventbrite has it, great! The styling looks good too. I've made a couple notes below to take care of before this feature is complete.

Functionality
- [x] Error handling. Currently in the login and sign up pages, when I click the submit button, I am redirected to the home page without getting signed in. Navigating back to the login/signup page shows the errors (which have persisted). The correct behavior when a user doesn't provide correct credentials would be to stay on the same page, render the errors, and clear them upon successful log in. 

User Interface
- [x] The green active input border is a nice UI touch. It's missing from the First and Last name input  boxes.
- [x] The demo login button is not centered

Great work! Please assign this issue for review when it's ready.

**Comment by anastassia-b** [comment]
Today we discussed how to implement error handling:  You could subscribe your sign up component subscribe to the slice of state that holds the current user. If the post/user request gives back errors, it will simply render the component. If the post/user request succeeds in logging in the user, it should dispatch(clearErrors()) and push them back to the events home page.

**Comment by anastassia-b** [comment]
Great job. The functionality and design is well done. Good attention to detail-- such as enabling the enter button to submit the form, and pre-filling the email from one view to the next. A small bug happens: when there are errors, and the user correctly inputs the information, it takes 2 clicks to login/signup for the form to go through. Otherwise, this MVP is complete.
