### ISSUE TITLE
PA Review: Hosting on Heroku

### ISSUE THREAD

**Issue by MikeSalisbury** [MikeSalisbury/eventbright#2]
- [x] Live project on Heroku
- [ ] Remove Minification Warnings
- [ ] Use devtools in dev environment

**Comment by MikeSalisbury** [comment]
https://eventbrightapp.herokuapp.com/?#/

**Comment by anastassia-b** [comment]
Sweet, the initial push is live and working. We'll close this issue after the final heroku deployment process is complete.
