### ISSUE TITLE
PA Review: Bookmark Events

### ISSUE THREAD

**Issue by MikeSalisbury** [MikeSalisbury/eventbright#4]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by MikeSalisbury** [comment]
- [x] bookmark functions properly; however, index does not re-render on toggle.

**Comment by anastassia-b** [comment]
Excellent, I can bookmark the events. In the future this can serve as information for a user profile page. Adding the pointer to the bookmark is a good affordance, if you want to do grey hover effects, that'd be good too.
