### ISSUE TITLE
PA Review: Events

### ISSUE THREAD

**Issue by MikeSalisbury** [MikeSalisbury/eventbright#5]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
Great progress on this feature. We discussed some action points before this MVP is marked as complete: 
- [x] Making the 2 vertical images horizontal on cloudinary for ease of styling.
- [x] Adding a new css class to the "listing privacy" container that does not have the width property. 
- [x] Style the events index page (particularly, the event info container to be the same height).
- [x] Style the event show page.

**Comment by anastassia-b** [comment]
The events index and the events show page look great! The images seem to be loading slowly, you could consider investigating this and optimizing it if you have time.
