### ISSUE TITLE
PA Review: Categories

### ISSUE THREAD

**Issue by MikeSalisbury** [MikeSalisbury/eventbright#6]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by MikeSalisbury** [comment]
- [x] bug with filter search - can't render index page after filtered search

**Comment by MikeSalisbury** [comment]
As we talked about, the main index would be where the user would filter events. the logo and browse event buttons trigger a fetch to all events listing all of them.

**Comment by anastassia-b** [comment]
Great job with the Categories! I can filter the events correctly. As you mentioned, the Eventbrite logo and the "Browse Events" button both lead back to all events, so adding an "All Events" filter button is up to your own discretion. Additionally, if you wanted to add the Category somewhere to the events show page, that could be nice. This MVP is complete.
