### ISSUE TITLE
Create Event Form Bugs

### ISSUE THREAD

**Issue by anastassia-b** [MikeSalisbury/eventbright#8]
There are several bugs with the create event form that should be addressed:

- [x] I shouldn't be able to go to the "Create Event" page if I'm not signed in. 
- [x] Bug: Uploading the image sometimes tries to submit the form.
- [x] Upon successful event creation, redirect to the index page or ideally, the new event show page.

Optional Notes
- [x] Maybe show that it's "optional" for event type and event topic.
- [x] Real website has both publish and make event live button, but I think for yours it might be nice to just have the bottom button. Less confusing.

**Comment by MikeSalisbury** [comment]
Hi Anastassia, could you clarify this a bit more: ' Currently, the event registration form redirects me back to the same page when there are errors.'

**Comment by anastassia-b** [comment]
Ah, yes. I tried to replicate the behavior I was commenting on, but I don't see it anymore. What I do see now is that if my form goes through, it doesn't take me to the event show page, it takes me to the "create event" page again. I think this behavior was fixed previously, so maybe the heroku version isn't the latest?

Optional
- [x] Make the delete ticket button smaller.

**Comment by anastassia-b** [comment]
Great work, all bugs have been fixed!
